"""empty message

Revision ID: db4061418c3e
Revises: ab0f4b6e5014
Create Date: 2016-05-30 09:01:03.554000

"""

# revision identifiers, used by Alembic.
revision = 'db4061418c3e'
down_revision = 'ab0f4b6e5014'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('vote_num', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'vote_num')
    ### end Alembic commands ###
